---
output:
  pdf_document: default
  html_document: default
---
<!--HOW TO COMPLETE THIS FORM:-->

<!--
1. Checkboxes in this document appear as follows: 

- [ ] This is a checkbox 

To check a checkbox, replace [ ] by [x], as follows: 

- [x] This is a checked checkbox 

 
2. For text answers, simply type the relevant text in the areas indicated. A blank line starts a new paragraph. 
 
3. Comments (like these instructions) provide additional instructions throughout the form. There is no need to remove them; they will not appear in the compiled document. 

4. If you are comfortable with Markdown syntax, you may choose to include any Markdown-compliant formatting in the form. For example, you may wish to include R or Python code chunks and compile this document in Quarto or R Markdown.
-->

This form documents the artifacts associated with the article (i.e., the data and code supporting the computational findings) and describes how to reproduce the findings.


# Part 1: Data

- [ ] This paper does not involve analysis of external data (i.e., no data are used or the only data are generated by the authors via simulation in their code).

<!--
If box above is checked and if no simulated/synthetic data files are provided by the authors, please skip directly to the Code section. Otherwise, continue.
-->

- [x] I certify that the author(s) of the manuscript have legitimate access to and permission to use the data used in this manuscript.

## Abstract

Datasets used in the real data analysis in the paper 'Spherically Embedded Time Series with Unknown Trend and Periodic Components', covering U.S. energy generational compositional time series and distributional time series from the New York City City bike sharing system. The two datasets are available in the 
Github repository <https://github.com/d5rhtkp4kc-alt/STPD/tree/main/real%20data/dataset>. The sources of each dataset are explicitly mentioned in the paper and are as follows: <https://www.eia.gov/electricity/data/browser/> (U.S. energy generational data) and <https://citibikenyc.com/system-data> (New York City City bike sharing system data).

## Availability


- [x] Data **are** publicly available.
- [ ] Data **cannot be made** publicly available.

If the data are publicly available, see the *Publicly available data* section. Otherwise, see the *Non-publicly available data* section, below.

### Publicly available data

- [ ] Data are available online at:

- [x] Data are available as part of the paper's supplementary material.

- [ ] Data are publicly available by request, following the process described here:

- [ ] Data are available through some other mechanism, described here:


<!-- If data are available by request to the authors or some other data owner, please make sure to explain the process of requesting access to the data and the details of how to access the specific data files needed. Details are generally best provided in README file(s) accompanying the materials.
-->

### Non-publicly available data

<!--
The Journal of the American Statistical Association requires authors to make data accompanying their papers available to the scientific community except in cases where: 1) public sharing of data would be impossible, 2) a synthetic/facsimile dataset in the same format as the real data is provided (recognizing that results may differ substantially from the real data analyses), and 3) the scientific value of the results and methods outweigh the lack of reproducibility.

Please discuss the lack of publicly available data. For example:
-	why data sharing is not possible,
-	what synthetic/facsimile data are provided, and 
-	why the value of the paper's scientific contribution outweighs the lack of reproducibility.
-->

## Description

### File format(s)

<!--
Check all that apply
-->
- [x] CSV or other plain text.
- [ ] Software-specific binary format (.Rda, Python pickle, etc.): 
- [ ] Standardized binary format (e.g., netCDF, HDF5, etc.): 
- [ ] Other (please specify):

### Data dictionary

<!--
A data dictionary provides information that allows users to understand the meaning, format, and use of the data.
-->

- [ ] Provided by authors in the following file(s): 
- [ ] Data file(s) is (are) self-describing (e.g., netCDF, HDF5, Zarr files)
- [x] Available at the following URL: <https://github.com/d5rhtkp4kc-alt/STPD/tree/main/real%20data/dataset>

### Additional Information (optional)

The folder 'real data/dataset' contains two datasets: US_energy.csv and trip.csv.

1. US_energy.csv --- US energy generation composition dataset downloaded from <https://www.eia.gov/electricity/data/browser/>. For details, see Section 6.1 of the paper.

2. trip.csv--- Preprocessed New York City Citi bike sharing system data with original dataset downloaded from <https://citibikenyc.com/system-data>. For details, see Section 6.2 of the paper.


# Part 2: Code

## Abstract

Code to reproduce all the numerical results in the paper 'Spherically Embedded Time Series with Unknown Trend and Periodic Components', available in the GitHub repository: <https://github.com/d5rhtkp4kc-alt/STPD>. It also contains Python code for TimePFN downloaded from <https://github.com/egetaga/TimePFN>.

## Description

### Code format(s)

<!--
Check all that apply
-->
- [x] Script files
    - [x] R
    - [x] Python
    - [ ] Julia
    - [ ] MATLAB
    - [ ] Other: 
- [ ] Package
    - [ ] R
    - [ ] Python
    - [ ] Julia
    - [ ] MATLAB toolbox
    - [ ] Other: 
- [x] Reproducible report 
    - [ ] Quarto or R Markdown 
    - [x] Jupyter notebook
    - [ ] Other:
- [ ] Shell script
- [ ] Other (please specify): 

### Supporting software requirements

<!--
Please cite all software packages in the References Section in similar fashion to paper citations, citing packages that are foundational to the research outcome (including packages that implement methods to which you compare your methods). You may elect to not cite packages used for supporting purposes. For R packages, note that running `citation('name_of_package')` often shows how the package authors wish to be cited.
-->

#### Primary software used

R version 4.5.1, Python 3.13.13

#### Libraries and dependencies used by the code

<!--
List packages (e.g., R or Python packages) and libraries here, including version numbers (e.g., version numbers for any R or Python packages used) if not otherwise documented with the materials provided (e.g., an `renv` lock file or Conda environment file or in a README).

If documented with the materials, indicate here where to find the package and version information.
-->

1. **R Packages**: ggplot2 (version 3.5.2), plot3D (version 1.4.1), ggforce (version 0.5.0), patchwork (version 1.3.0), psych (version 2.5.3), osqp (version 0.6.3.3), transport (version 0.15-4), easyCODA (version 0.40.2), tidyr (version 1.3.1), movMF (version 0.2-9), trust (version 0.1-8), parallel (version 4.5.0), foreach (version 1.5.2), doSNOW (version 1.0.20), xtable (version 1.8-4).

2. **Python Packages**: Standard library modules for Python 3.13.13 --- copy, os, random, sys, time. Third-party packages --- numpy (version 2.4.4), pandas (version 3.0.2), torch (version 2.12.0), matplotlib (version 3.10.8), scipy (version 1.17.1).

### Supporting system/hardware requirements (optional)

<!--
OPTIONAL: System/hardware requirements including operating system with version number, access to cluster, GPUs, etc.
-->

### Parallelization used

- [ ] No parallel code used
- [ ] Multi-core parallelization on a single machine/node
    - Number of cores used: 
- [x] Multi-machine/multi-node parallelization 
    - Number of nodes and cores used: 200

<!--
For more complicated situations, more details can be provided in README file(s) that accompany the code.
-->

### License

- [x] MIT License (default)
- [ ] BSD 
- [ ] GPL v3.0
- [ ] Creative Commons
- [ ] Other: (please specify)


### Additional information (optional)

<!--
OPTIONAL: By default, supplementary material will be archived on figshare by JASA. Authors are strongly encouraged to also make their code available in a public code repository, such as on GitHub, GitLab, or BitBucket. If relevant, please provide unique identifier/DOI/version information (e.g., a Git commit ID, branch, release, or tag). 

If the code and workflow are provided together, this section may be omitted, with information provided in the "Location" section below.
-->

# Part 3: Reproducibility workflow

<!--
The materials provided should provide a straightforward way for reviewers and readers to reproduce analyses with as few steps as possible. 
-->

## Scope

The provided workflow reproduces:

- [x] Any numbers provided in text in the paper
- [x] The computational method(s) presented in the paper (i.e., code is provided that implements the method(s))
- [x] All tables and figures in the paper
- [ ] Selected tables and figures in the paper, as explained and justified below:

## Workflow

### Location

The workflow is available:

<!--
Check all that apply, and in the case of a Git repository include unique identifier, such as specific commit ID, branch, release, or tag.
-->
- [ ] As part of the paper’s supplementary material.
- [x] In this Git repository: README.md
- [ ] Other (please specify):

<!--
Indicate where the materials (generally including the code, unless in a separate location and indicated in the previous section) are available.

We strongly encourage authors to place their materials (but not large datasets) in a Git repository hosted on a site such as GitHub, GitLab, or BitBucket. If the repository is private during the review process, please indicate the location where it will be available publicly upon publication.

If materials are provided in a Git repository, to ensure long-term availability, make sure that you have also either included the materials in the supplementary material (e.g., as a zip file obtained directly from the Git hosting service) or placed them in a permanent archive with a DOI, such as in Zenodo.
-->


### Format(s)

<!--
Check all that apply
-->
- [ ] Single master code file 
- [ ] Wrapper (shell) script(s)
- [ ] Self-contained Quarto, R Markdown file, Jupyter notebook, or other literate programming approach
- [x] Text file (e.g., a readme-style file) that documents workflow
- [ ] Makefile
- [ ] Other (more detail in *Instructions* below)

### Instructions

**Procedure to reproduce Figures 1, 2, 3, and S1**

Step 1. Run figure/visual_plot.R to reproduce Figures 1, 2, 3, and S1.

**Procedure to reproduce simulation results on prediction (recommend using high performance computer)**

Step 1. Run simulation/prediction.R to get required statistical model results needed for Figures 4, S3, and S4.

Step 2. Run simulation/python_data_generation.R to generate required simulated data for neural network results needed for Figures 4, S3, and S4.

Step 3. Run simulation/LSTM_sim.ipynb to generate required LSTM model results needed for Figures 4, S3, and S4.

Step 4. Run simulation/TimePFN_sim.ipynb to generate required TimePFN model results needed for Figures 4, S3, and S4.

Step 5. Run simulation/prediction_figure.R to reproduce Figures 4, S3, and S4.

**Procedure to reproduce simulation results on estimation (recommend using high performance computer)**

Step 1. Run simulation/estimation.R to reproduce Tables S1, S2, and S3. 

**Procedure to reproduce real data results**

Step 1. Run real data/real_data_engergy.R to reproduce Figures 5, 6, and S2, and to generate required statistical model results needed for Figure S5.

Step 2. Run real data/real_data_trip.R to reproduce Figures 7, 8, S6, S7, S8, S9, and S10, and to generate required statistical model results needed for Figure S11.

Step 3. Run real data/LSTM_real.ipynb to generate required LSTM model results needed for Figures S5 and S11.

Step 4. Run real data/TimePFN_real.ipynb to generate required TimePFN model results needed for Figures S5 and S11.

Step 5. Run real data/prediction_figure.R to reproduce Figures S5 and S11.

### Expected run-time

Approximate time needed to reproduce the analyses on a standard desktop machine:

- [ ] < 1 minute
- [ ] 1-10 minutes
- [ ] 10-60 minutes
- [ ] 1-8 hours
- [ ] > 8 hours
- [x] Not feasible to run on a desktop machine, as described here: the simulation requires high performance computers, while the real data analysis results can be reproduced on a standard desktop machine for around 4 hours.

<!--
For more complicated situations, including cases where the run-time varies greatly across different analyses, more details can be provided in README file(s) that accompany the materials.
-->

### Additional information (optional)

<!--
OPTIONAL: Additional documentation provided (e.g., R package vignettes, demos or other examples) that show how to use the provided code/software in other settings.
-->

# Notes (optional)

<!--
OPTIONAL: Any other relevant information not covered on this form. 
-->
